baseURL = 'https://nichoffs.github.io/'
languageCode = 'en-us'
title = 'Nic Hoffs Blog'
theme = 'xmin'


[[menu.main]]
name = "About"
url = '/about/'
weight = 0

[[menu.main]]
name = "Home"
url ='/'
weight = 1

[[menu.main]]
name = "Posts"
url ='/post/'
weight = 2

[params]
  customCSS = ["css/custom.css"]

